### ISSUE TITLE
IOError when installing from PyPI

### ISSUE THREAD

**Issue by mrsanders** [stephrdev/django-formwizard#18]
Attempted to install django-formwizard 1.0 from PyPi using pip. This gives the error:

```
C:\Python26\Scripts>pip install django-formwizard
Downloading/unpacking django-formwizard
  Downloading django-formwizard-1.0.tar.gz
  Running setup.py egg_info for package django-formwizard
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "C:\Python26\Scripts\build\django-formwizard\setup.py", line 11, in <module>
        long_description=read("README.rst"),
      File "C:\Python26\Scripts\build\django-formwizard\setup.py", line 5, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    IOError: [Errno 2] No such file or directory: 'C:\\Python26\\Scripts\\build\\django-formwizard\\README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "C:\Python26\Scripts\build\django-formwizard\setup.py", line 11, in <module>

    long_description=read("README.rst"),

  File "C:\Python26\Scripts\build\django-formwizard\setup.py", line 5, in read

    return open(os.path.join(os.path.dirname(__file__), fname)).read()

IOError: [Errno 2] No such file or directory: 'C:\\Python26\\Scripts\\build\\django-formwizard\\README.rst'

----------------------------------------
Command python setup.py egg_info failed with error code 1
Storing complete log in C:\Documents and Settings\msanders\Application Data\pip\pip.log
```

The 'README.rst' file is indeed missing from the build directory. Same error obtained when run on OS X.

**Comment by stephrdev** [comment]
Thank you for the hint! I just updated the package on PyPI.

**Comment by mrsanders** [comment]
Great - thanks for your quick response.
